config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, presence: true
    belongs_to :user
    belongs_to :post 
end

app/models/post.rb
class Post < ApplicationRecord
    validates :tittle, presence: true
    validates :body, presence: true
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_post

    @@current_post_id

    def current_post(id:)
        @@current_post_id = id
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @comment = Comment.all
  end

  def new
    @post_id = params[:post_id]
    @comment = Comment.new(:post_id => params[:post_id])
  end

  def edit
  end

  def create
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    # @comment.post_id = post_id
    @comment.save

    redirect_to post_path(@comment.post_id)
  end

  def show
  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_path(@@current_post_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    current_post( id: @post.id )
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:tittle, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for @comment do |f| %>

    <%= f.hidden_field :post_id, required: true, class: 'form-control', value:@post_id  %>
    <div class="field">
        <%= f.label :comment %>
        <%= f.text_field :body %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tittle %>
    <%= form.text_field :tittle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

<h1> fakebook </h1>

<div>
  <% if !user_signed_in? %>
    <%= link_to("login", {:controller => "devise/sessions", :action => "new"} ) %>
    <%= link_to("signup", {:controller => "devise/registrations", :action => "new"} ) %>
  <% else %>
    
    <p><%= "Welcome #{current_user.email}" %>
       <%= link_to "Log out", destroy_user_session_path, :action => "destroy", :method => :delete %>  
    </p>
  <% end %>
</div>
<br><br>


<div>
  <h2>Posts </h2> 
  <% if user_signed_in? %>
    <%= link_to 'New Post', new_post_path %> 
  <% end %>
</div>
<br>


<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.tittle %></td>
        <td><%= post.body %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to 'Show Comments', post %></td>
        <% if post.user == current_user %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

<p>
  <strong>Tittle:</strong>
  <%= @post.tittle %> |
  <%= link_to 'Back', posts_path %>
</p>

<pre>
  <strong>Body:</strong>
  <%= @post.body %>
  <% if user_signed_in? %>
    <%= link_to 'add comment', new_comment_path(:post_id => @post.id) %>
  <% end %>
</pre>

<table>
  <thead>
    <tr>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body%></td>
        <% if user_signed_in? && (current_user.id == @post.user_id || current_user.id == comment.user_id) %>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>